/*
 *  DBPrefKeys.h
 *  DrawBerry
 *
 *  Created by Raphael Bost on 16/07/07.
 *  Copyright 2007 __MyCompanyName__. All rights reserved.
 *
 */

#define DBToolSelectorMode  @"Tool Selector Mode"
#define DBUnitName  @"Unit Name"
#define DBDonateReminder @"Donate Reminder Version"

#define DBViewInspectorOpened @"viewInspector Opened"
#define DBObjectInspectorOpened @"objectInspector Opened"
#define DBLayerWindowOpened @"layerWindow Opened"
#define DBMagGlassPanelOpened @"magGlassPanel Opened"
#define DBUndoWindowOpened @"undoWindow Opened"
#define DBColorSwatchOpened @"colorSwatch Opened"
#define DBShapeLibraryOpened @"shapeLibrary Opened"

// be careful with following keys as they are automaticaly generated by GBarView class to autosave
#define DBPagePanelGridCollapsed @"gridWindow Grid Collapsed"
#define DBPagePanelPageCollapsed @"gridWindow Page Collapsed"
#define DBPagePanelRulersCollapsed @"gridWindow Rulers Collapsed"
#define DBShapePanelRulersCollapsed @"shapeWindow Stroke Collapsed"
#define DBShapePanelArrowsCollapsed @"shapeWindow Arrows Collapsed"
#define DBShapePanelFillCollapsed @"shapeWindow Fill Collapsed"
#define DBShapePanelShadowCollapsed @"shapeWindow Shadow Collapsed"
#define DBShapePanelTextCollapsed @"shapeWindow Text Collapsed"
#define DBShapePanelGeometryCollapsed @"shapeWindow Geometry Collapsed"

#define DBNewDocumentAtStartup @"New Doc at startup"
#define DBDefaultTemplateTag @"Default Template"

/* Notifs name sent by the preference controller */
#define DBDidChangeUnitNotificationName  @"Unit Did Change"